version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "src/StandardNotesEditor.App/frontend"
    open-pull-requests-limit: 2
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "monthly"
