version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "src/StandardNotesEditor.App/jslib"
    schedule:
      interval: "weekly"
