name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: restore
        run: dotnet restore

      - name: build
        run: dotnet build -c Release --no-restore

      - name: publish
        run: dotnet publish src/StandardNotesEditor.App/StandardNotesEditor.App.csproj -c Release --no-build -o out

      - name: archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: out/
          if-no-files-found: error
